#!/usr/bin/env python
from __future__ import with_statement
import os
import shutil
import subprocess
import sys
import tempfile

# 501: line too long
ignore_codes = ['E501', 'E731']

def system(*args, **kwargs):
    kwargs.setdefault('stdout', subprocess.PIPE)
    proc = subprocess.Popen(args, **kwargs)
    out, err = proc.communicate()
    return out


def main():
    files = []
    output = system('git', 'ls-files').decode("utf-8")
    for tmp_file in output.split():
        if tmp_file.endswith('.py'):
            files.append(tmp_file)

    tempdir = tempfile.mkdtemp()
    for name in files:
        filename = os.path.join(tempdir, name)
        filepath = os.path.dirname(filename)
        if not os.path.exists(filepath):
            os.makedirs(filepath)
        with open(filename, 'w') as f:
            system('git', 'show', ':{0}'.format(name), stdout=f)

    args = ['pep8']
    args.extend(('--ignore', ','.join(ignore_codes)))
    args.append('.')
    output = system(*args, cwd=tempdir)
    shutil.rmtree(tempdir)
    if output:
        print(output)
        sys.exit(1)


if __name__ == '__main__':
    main()
